# Keterangan 

In [ ]:
Muhamad Faris Rabi (09011281823032)

Hasil pertandingan liga inggris liverpool dari tahun 1993-2018 menggunakan Support Vector Mechine (SVM)

Support Vector Machine(SVM) merupakan sebuah algoritma klasifikasi untuk data linear dan non-linear.
SVM menggunakan mapping non-linear untuk mentransformasikan training data awal ke dimensi yang lebih tinggi.


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# **DATASET LIVERPOOL**

In [8]:
dataset=pd.read_csv('liverpoolfcstats.csv')


Keterangan home/away(Tuan rumah/Tamu) , jadwal main dan hasil pertandingan

In [ ]:
print(dataset.head())

   Unnamed: 0      Date   HomeTeam        AwayTeam  FTHG  FTAG FTR  HTHG  \
0           4  14/08/93  Liverpool  Sheffield Weds     2     0   H   NaN   
1          20  18/08/93        QPR       Liverpool     1     3   A   NaN   
2          33  22/08/93    Swindon       Liverpool     0     5   A   NaN   
3          40  25/08/93  Liverpool       Tottenham     1     2   A   NaN   
4          49  28/08/93  Liverpool           Leeds     2     0   H   NaN   

   HTAG  HTR   Season  
0   NaN  NaN  1993-94  
1   NaN  NaN  1993-94  
2   NaN  NaN  1993-94  
3   NaN  NaN  1993-94  
4   NaN  NaN  1993-94  


In [41]:
X=dataset.iloc[:,2:4]

In [10]:
for a in X:
    a.replace(" ","")

Jadwal pertandingan Liverpool

In [11]:
print(X)

      HomeTeam        AwayTeam
0    Liverpool  Sheffield Weds
1          QPR       Liverpool
2      Swindon       Liverpool
3    Liverpool       Tottenham
4    Liverpool           Leeds
..         ...             ...
953  Liverpool     Bournemouth
954  West Brom       Liverpool
955  Liverpool           Stoke
956    Chelsea       Liverpool
957  Liverpool        Brighton

[958 rows x 2 columns]


In [12]:
y=dataset.iloc[:,6].values

Keterangan hasil pertandingan
A = WIN (MENANG)
H = LOSE (KALAH)
D = DRAW (IMBANG / SCORE SAMA)

In [13]:
print(y)

['H' 'A' 'A' 'A' 'H' 'H' 'A' 'H' 'H' 'D' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'H'
 'D' 'D' 'D' 'D' 'A' 'D' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'A'
 'D' 'H' 'A' 'A' 'A' 'H' 'A' 'H' 'A' 'D' 'H' 'D' 'H' 'H' 'H' 'H' 'A' 'H'
 'H' 'H' 'H' 'D' 'D' 'D' 'D' 'A' 'H' 'A' 'H' 'A' 'D' 'D' 'D' 'A' 'H' 'A'
 'H' 'D' 'H' 'A' 'A' 'H' 'H' 'A' 'D' 'H' 'H' 'H' 'H' 'H' 'A' 'H' 'H' 'H'
 'H' 'D' 'D' 'A' 'H' 'H' 'A' 'D' 'H' 'D' 'A' 'H' 'H' 'D' 'H' 'D' 'H' 'A'
 'D' 'A' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'D' 'H' 'D' 'D' 'D' 'H' 'D' 'A'
 'H' 'A' 'H' 'A' 'H' 'H' 'H' 'A' 'D' 'D' 'A' 'A' 'H' 'H' 'D' 'D' 'A' 'H'
 'D' 'H' 'A' 'H' 'D' 'H' 'H' 'D' 'A' 'A' 'A' 'D' 'A' 'H' 'H' 'D' 'D' 'A'
 'D' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'D' 'H' 'A' 'A' 'A' 'A' 'H' 'H' 'A'
 'H' 'D' 'H' 'D' 'A' 'D' 'D' 'H' 'H' 'D' 'A' 'D' 'H' 'D' 'H' 'H' 'H' 'H'
 'A' 'D' 'A' 'H' 'H' 'D' 'H' 'D' 'D' 'H' 'H' 'A' 'A' 'A' 'H' 'H' 'H' 'H'
 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'D' 'D' 'A' 'A' 'A' 'H' 'D'
 'H' 'H' 'A' 'A' 'H' 'A' 'H' 'A' 'D' 'A' 'D' 'H' 'D

In [14]:
X['Match']=X['HomeTeam']+X['AwayTeam']

In [15]:
print(X)

      HomeTeam        AwayTeam                    Match
0    Liverpool  Sheffield Weds  LiverpoolSheffield Weds
1          QPR       Liverpool             QPRLiverpool
2      Swindon       Liverpool         SwindonLiverpool
3    Liverpool       Tottenham       LiverpoolTottenham
4    Liverpool           Leeds           LiverpoolLeeds
..         ...             ...                      ...
953  Liverpool     Bournemouth     LiverpoolBournemouth
954  West Brom       Liverpool       West BromLiverpool
955  Liverpool           Stoke           LiverpoolStoke
956    Chelsea       Liverpool         ChelseaLiverpool
957  Liverpool        Brighton        LiverpoolBrighton

[958 rows x 3 columns]


In [16]:
X2=X.iloc[:,2]

In [17]:
print(X2)

0      LiverpoolSheffield Weds
1                 QPRLiverpool
2             SwindonLiverpool
3           LiverpoolTottenham
4               LiverpoolLeeds
                ...           
953       LiverpoolBournemouth
954         West BromLiverpool
955             LiverpoolStoke
956           ChelseaLiverpool
957          LiverpoolBrighton
Name: Match, Length: 958, dtype: object


In [18]:
for match in X2:
    match.replace(" ","")
print(X2)

0      LiverpoolSheffield Weds
1                 QPRLiverpool
2             SwindonLiverpool
3           LiverpoolTottenham
4               LiverpoolLeeds
                ...           
953       LiverpoolBournemouth
954         West BromLiverpool
955             LiverpoolStoke
956           ChelseaLiverpool
957          LiverpoolBrighton
Name: Match, Length: 958, dtype: object


In [19]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X2 = X2.values.reshape(len(y), 1)
# X2 = np.array(ct.fit_transform(X2))
# print(X2)

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X2 = le.fit_transform(X2)
print(X2)
X2 = X2.reshape(len(X2),1)


[60 82 90 66 46 14 28 17 13 24 55 73 61 69 77 25 85 57 65 91 84 71 21 49
 80 48 78 86 22 38  4 41 37  0 74 59 96 45 52 94 53  1 15 24 86 69 74 77
 60 25  4 71 21 82 54 37 17 66 14 39 13 23 48 22 53 45 41 79 57 85 52 38
 49 91 61 46  0 73 47 78 96  1 94 28 60 22 91 57 96 28 30 74 38 86 48 77
 41 94 76 61  6 49 24 13 54 85 46  1 66 82  4 25 71 37 79 52 14 69 17 51
  0 73 76 24 63 14 61 23 37 94 74 40  4 22 41 71 91 60 51 54 77 47 86 13
 69 25 16 46 28  1 52 79  0 38 88 17 49 66 96 85 96 47  4 22 60 86 25 94
 37 17 40  6 66 26  0 49 15 38 46 77 71 23 52 28 61 85 41  1 30 91  2 74
 39 14 13 69 24 16 86 24 77 38 94 36 74 37 17 54 23 40 46  1 28 91 96 60
 76 52  0 61 14 51 12 69 13 16 41 79 22 25 47  4 66 49 85 71 85 67 76 22
 24 49 23 41  1 37 86 69 32 40 88 94 60 38 77 71 91 92 51 46  0 74 63 25
 16 52 14 66 96 17 13 47 61  8 32  0 86 25 48 94 63 13 16 47 41 22 38 91
 77 36 45 74 24 76 61  1 51 73 69 88 23 40 49 21 46 17 66 14  8 52 37 12
 69  6 25 17 66 77 46 23 12 49  4 63 16 51 42 13 24

In [21]:
# trainDfDummies = pd.get_dummies(X2, columns=['Match'])


In [22]:
# print(trainDfDummies)

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)
y = y.reshape(len(y),1)

[2 0 0 0 2 2 0 2 2 1 2 1 2 2 2 2 2 2 1 1 1 1 0 1 0 2 1 2 2 2 2 2 2 2 2 0 1
 2 0 0 0 2 0 2 0 1 2 1 2 2 2 2 0 2 2 2 2 1 1 1 1 0 2 0 2 0 1 1 1 0 2 0 2 1
 2 0 0 2 2 0 1 2 2 2 2 2 0 2 2 2 2 1 1 0 2 2 0 1 2 1 0 2 2 1 2 1 2 0 1 0 0
 2 1 2 2 2 2 2 1 2 1 1 1 2 1 0 2 0 2 0 2 2 2 0 1 1 0 0 2 2 1 1 0 2 1 2 0 2
 1 2 2 1 0 0 0 1 0 2 2 1 1 0 1 0 2 1 2 2 2 2 2 1 2 0 0 0 0 2 2 0 2 1 2 1 0
 1 1 2 2 1 0 1 2 1 2 2 2 2 0 1 0 2 2 1 2 1 1 2 2 0 0 0 2 2 2 2 0 2 1 2 2 2
 2 1 2 2 2 1 1 0 0 0 2 1 2 2 0 0 2 0 2 0 1 0 1 2 1 2 2 2 0 2 2 2 1 2 2 0 1
 2 0 1 1 1 0 2 0 2 0 1 2 0 1 2 2 2 1 2 2 1 1 2 0 2 2 2 2 2 2 2 0 0 2 2 2 0
 1 1 2 1 2 1 2 1 0 0 2 0 0 2 1 0 2 2 0 0 2 0 1 0 0 2 1 2 0 2 1 2 0 0 1 1 2
 1 1 0 2 0 0 1 0 2 0 2 2 0 2 2 2 2 0 2 1 1 1 0 2 0 2 0 2 2 2 1 2 0 2 2 1 1
 1 2 1 0 1 0 1 2 2 0 2 2 2 0 2 0 0 2 0 1 1 0 0 2 2 0 2 2 0 0 1 2 1 0 2 1 0
 2 2 1 1 1 2 1 2 2 2 1 2 2 0 1 0 2 0 1 1 2 2 2 2 2 2 0 2 1 0 2 2 2 1 2 1 2
 0 2 0 0 0 2 0 2 2 2 1 2 2 2 1 0 2 1 2 2 1 2 1 1 1 0 2 2 2 0 2 0 0 2 2 2 0
 2 1 2 2 1 2 2 0 2 2 1 2 

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size = 1/3, random_state = 0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.62602937]
 [ 0.2723843 ]
 [ 0.44920683]
 [ 1.19186147]
 [ 1.01503894]
 [-0.04589626]
 [ 0.51993585]
 [ 1.61623555]
 [ 0.30774881]
 [-0.25808329]
 [ 1.05040344]
 [-0.39954132]
 [-0.43490583]
 [-1.67266355]
 [-0.89464441]
 [ 0.62602937]
 [-0.2934478 ]
 [-1.67266355]
 [ 1.61623555]
 [-0.8239154 ]
 [-0.2934478 ]
 [ 0.16629078]
 [-1.49584102]
 [-0.08126076]
 [-0.04589626]
 [-1.49584102]
 [ 1.3333195 ]
 [ 1.40404851]
 [-0.25808329]
 [-0.8239154 ]
 [-1.24828947]
 [ 0.8028519 ]
 [-1.56657003]
 [-0.75318638]
 [ 1.40404851]
 [-0.25808329]
 [ 0.62602937]
 [ 0.37847782]
 [-1.67266355]
 [ 1.29795499]
 [-1.70802806]
 [-1.46047651]
 [ 0.44920683]
 [ 0.87358091]
 [ 1.19186147]
 [ 0.62602937]
 [-1.24828947]
 [ 0.13092628]
 [-0.36417681]
 [-1.00073793]
 [ 0.34311331]
 [-1.56657003]
 [-0.01053175]
 [ 1.43941301]
 [-0.22271879]
 [-1.67266355]
 [-0.8592799 ]
 [ 1.3333195 ]
 [ 0.97967443]
 [-0.64709287]
 [ 0.16629078]
 [ 0.73212289]
 [-0.43490583]
 [ 1.368684  ]
 [-0.01053175]
 [ 1.40404851]
 [ 0.90894

# sklearn SVC ( Kernel , Random-state )

In [30]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [31]:
# y_pred = classifier.predict(X_test)
print("np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)")


np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)


In [32]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# accuracy_score(y_test, y_pred)

In [33]:
# I=input('Enter match as LiverpoolLeeds')
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# I = le.fit_transform([I])
# I = I.reshape(len(I),1)
# print(sc.transform(I))
# print(classifier.predict(sc.transform(I)))

In [34]:
# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()
# classifier.fit(X_train, y_train)

In [35]:
# I=input('Enter match as LiverpoolLeeds')
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# I = le.fit_transform([I])
# I = I.reshape(len(I),1)
# print(sc.transform(I))
# print(classifier.predict(sc.transform(I)))

In [36]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# accuracy_score(y_test, y_pred)

In [37]:
# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)


Prediksi score saat sehari pertandingan belum dimulai

# Sklear prepprocessing

In [38]:
I=input('Enter match as LiverpoolLeeds')
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
I = le.fit_transform([I])
I = I.reshape(len(I),1)
print(sc.transform(I))
print(classifier.predict(sc.transform(I)))

Enter match as LiverpoolLeedscity
[[-1.70802806]]
[0]


In [39]:
y_pred = classifier.predict(X_test)

# Test a sample

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 38   0  54]
 [ 23   0  55]
 [ 24   0 126]]


0.5125

# **Referensi**

Referensi = https://github.com/shubhamshrimant/Football_Prediction/commit/9dd130de7d238630c8fc44ebb0db58566abc13f8

dataset = https://github.com/shubhamshrimant/Football_Prediction.git