## **Breast Cancer Prediction with Artificial Neural Network (ANN)**

   Jaringan saraf tiruan adalah salah satu alat utama yang digunakan dalam pembelajaran mesin. Seperti yang ditunjukkan oleh bagian "saraf" dari namanya, mereka adalah sistem yang diilhami oleh otak yang dimaksudkan untuk meniru cara kita sebagai manusia belajar.

  Jaringan saraf terdiri dari lapisan masukan dan keluaran, serta (dalam banyak kasus) lapisan tersembunyi yang terdiri dari unit yang mengubah masukan menjadi sesuatu yang dapat digunakan lapisan keluaran. Mereka adalah alat yang sangat baik untuk menemukan pola yang terlalu kompleks atau banyak bagi programmer manusia untuk mengekstrak dan mengajarkan mesin untuk mengenali.Jaringan saraf juga disebut "perceptrons".
    
   Jaringan saraf telah menjadi bagian utama dari kecerdasan buatan dalam beberapa dekade terakhir. Hal ini disebabkan oleh munculnya teknik yang disebut "propagasi mundur", yang memungkinkan jaringan menyesuaikan lapisan neuron tersembunyi mereka dalam situasi di mana hasilnya tidak sesuai dengan apa yang diharapkan pembuatnya.

**In this kernel, artificial neural network (ANN) concept has been explained and implemented by using Keras.
Link Dataset https://www.kaggle.com/armagansarikey/prediction-with-artificial-neural-network-keras**

Pada tugas ini, Saya menggunakan Model Artifcial Neural Network (ANN) untuk membuat prediksi dari Breast Cancer dengan menggunakan library keras dalam membantu memprediksi seseorang yang memiliki kemungkinan terkena kanker payudara.

## Loading Dataset

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("input"))

# Any results you write to the current directory are saved as output.

['Breast_cancer_data.csv', 'Churn_Modelling.csv', 'seattleWeather_1948-2017.csv']


### Library yang digunakan

**Library Numpy**

* NumPy berfungsi untuk mengolah angka dalam bentuk array .

**Library pandas**
* Pandas berfungsi untuk membaca, mengelola data yang terdapat pada dataset.

**Library Matplotlib**
* Matplotlib dapat membantu dalam memvisualisasikan ke dalam bentuk plot grafik agar mudah untuk dipahami# 

In [2]:
data = pd.read_csv('input/Breast_cancer_data.csv')
data.head(569)

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     diagnosis  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
564          0  
565          0  
566          0  
567          0  
568          1  

[569 rows x 6 columns]

* **Mengambil data dari Dataset yang selanjutnya akan diproses. Pada bagian ini kita dapat dapat menentukan jumlah data yang ingin kita proses, dengan mengubah angka pada data.head()**

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   mean_radius      569 non-null    float64
 1   mean_texture     569 non-null    float64
 2   mean_perimeter   569 non-null    float64
 3   mean_area        569 non-null    float64
 4   mean_smoothness  569 non-null    float64
 5   diagnosis        569 non-null    int64  
dtypes: float64(5), int64(1)
memory usage: 26.8 KB


* **Menampilkan informasi yang terdapat pada dataset seperti pada data diatas terdapat 6 kolom dan juga tipe data dari setiap kolom dari dataset.**

In [4]:
smoothness = data['mean_smoothness'] > 1.0
smoothness.values

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [5]:
X = data.iloc[:,0:5].values
Y = data.iloc[:,5].values

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

## Features Scaling
* Sekarang mari terapkan penskalaan fitur. Penskalaan memastikan bahwa hanya karena beberapa fitur berukuran besar, model tidak akan menggunakannya sebagai prediktor utama.
* **Dalam metode jaringan syaraf tiruan (Artificial Neural Network), variabel bebas yaitu data masukan harus dalam interval [0,1].**

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

## Compile ANN
**Menyusun classifier.** Menggunakan adam optimizer. Menggunakan **binary_crossentropy untuk fungsi kerugian**.

In [8]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

# Hidden layers and input layer are  added.
classifier.add(Dense(3, kernel_initializer="uniform", activation = 'relu', input_dim = 5))

classifier.add(Dense(3, kernel_initializer="uniform", activation = 'relu'))

# Output layer
classifier.add(Dense(1, kernel_initializer="uniform", activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, epochs = 50)

# Prediction
y_pred = classifier.predict(X_test)

Using TensorFlow backend.
C:\Users\M_ImamR\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\M_ImamR\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\M_ImamR\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\M_ImamR\anaconda3\lib\site-packages\tensorflow\python\framework\d

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/50
381/381 [==============================] - 0s 920us/step - loss: 0.6927 - accuracy: 0.5722
Epoch 2/50
381/381 [==============================] - 0s 73us/step - loss: 0.6913 - accuracy: 0.6194
Epoch 3/50
381/381 [==============================] - 0s 80us/step - loss: 0.6897 - accuracy: 0.6194
Epoch 4/50
381/381 [==============================] - 0s 81us/step - loss: 0.6879 - accuracy: 0.6194
Epoch 5/50
381/381 [==============================] - 0s 78us/step - loss: 0.6858 - accuracy: 0.6194
Epoch 6/50
381/381 [==============================] - 0s 89us/step - loss: 0.6825 - accuracy: 0.6194
Epoch 7/50
381/381 [==============================] - 0s 80us/step - loss: 0.6781 - accuracy: 0.6194
Epoch 8/50
381/381 [==============================] - 0s 74us/step - loss: 0.6721 - accuracy: 0.6194
Epoch 9/50
381/381 [==============================] - 0s 76us/step - loss: 0.6640 - accuracy: 0.

In [9]:
y_pred

array([[0.27575248],
       [0.7948176 ],
       [0.964008  ],
       [0.9751274 ],
       [0.94538885],
       [0.94672894],
       [0.98458976],
       [0.9768889 ],
       [0.9967948 ],
       [0.98985755],
       [0.5383309 ],
       [0.30659416],
       [0.9954089 ],
       [0.328563  ],
       [0.2085185 ],
       [0.13196343],
       [0.98974633],
       [0.01917669],
       [0.02933773],
       [0.01556399],
       [0.8713334 ],
       [0.11338428],
       [0.8459732 ],
       [0.9742149 ],
       [0.02385882],
       [0.9919205 ],
       [0.9978354 ],
       [0.17178407],
       [0.9718044 ],
       [0.06032223],
       [0.98201734],
       [0.0449872 ],
       [0.9253778 ],
       [0.11911711],
       [0.9970855 ],
       [0.28322202],
       [0.962945  ],
       [0.08290741],
       [0.7818792 ],
       [0.1307317 ],
       [0.17545676],
       [0.99839   ],
       [0.19388875],
       [0.99045515],
       [0.9433503 ],
       [0.00912625],
       [0.9979292 ],
       [0.722

### Membuat Prediksi


In [10]:
y_pred = classifier.predict(X_test)
y_pred = [ 1 if y>=0.5 else 0 for y in y_pred ]

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
print("Accuracy in % : "+ str(accuracy*100)+"%")
print ('Accuracy score: ', accuracy_score(y_test, y_pred))

[[ 63   4]
 [ 10 111]]
Accuracy in % : 92.5531914893617%
Accuracy score:  0.925531914893617


# Kesimpulan

Berdasarkan hasil dari confusion matrix, prediksi kanker payudara cukup berhasil dengan menghasilkan tingkat akurasi dalam memprediksi kanker yaitu **0.92 atau 92%.** 

**Sumber : https://www.kaggle.com/armagansarikey/prediction-with-artificial-neural-network-keras**